//Copyright (c) 2023, the Dart project authors.  Please see the AUTHORS file
//for details. All rights reserved. Use of this source code is governed by a
//BSD-style license that can be found in the LICENSE file.




struct XRAnchor
{
}

()

pub extern requestPersistentHandle(this: js_object, [], [])
pub extern delete(this: js_object, [], [])
pub extern getanchorSpace(this: js_object): web webxr.kk/XRSpace
	c inline "getObjectField(#1, \"anchorSpace\")"
struct XRAnchorSet
{
}

()


