//Copyright (c) 2023, the Dart project authors.  Please see the AUTHORS file
//for details. All rights reserved. Use of this source code is governed by a
//BSD-style license that can be found in the LICENSE file.




struct EXT_blend_minmax
{
}

(pub extern MIN_EXT(): webgl1.kk/GLenum
	c inline "getConstant(\"MIN_EXT\")", pub extern MAX_EXT(): webgl1.kk/GLenum
	c inline "getConstant(\"MAX_EXT\")")

