//Copyright (c) 2023, the Dart project authors.  Please see the AUTHORS file
//for details. All rights reserved. Use of this source code is governed by a
//BSD-style license that can be found in the LICENSE file.




struct WEBGL_debug_renderer_info
{
}

(pub extern UNMASKED_VENDOR_WEBGL(): webgl1.kk/GLenum
	c inline "getConstant(\"UNMASKED_VENDOR_WEBGL\")", pub extern UNMASKED_RENDERER_WEBGL(): webgl1.kk/GLenum
	c inline "getConstant(\"UNMASKED_RENDERER_WEBGL\")")

