import common
import kk-builder

// TODO:
// 
// _typedef
// _topLevelGetter
// _typeReference
// _urlForType - if needed
// _overridableMember
// _constructor
// _objectLiteral
// _operation
// _getterSetter
// _attribute
// _constant
// _field
// _property / properties
// _operations
// _cssStyleDeclarationProperties
// _elementConstructors
// _extension
// _extensionType
// _interfaceLike
// _library
// generateRootImport
// translate